# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ad02e72c2133c191f5025b65b38e3b7138c289768d0ea572bdab119131433430d37ab3041aab47d6dbf0d5c7c3c57599e6831fdbc761fcc54de3cca1e5ec124b

test:
  secret_key_base: 0481abb749cb0055ca8661c29a8cef051529c9bbb463535f19c559c72b5942af98eb8b704b35dd13044951263da2899c51bc30d7c37c541702055c492dad885f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
